export type PaymentGatewayCatalogItem = {
  value: string;
  label: string;
  region?: string;
  supportLevel: 'supported' | 'planned';
};

export const SUPPORTED_PAYMENT_GATEWAYS = new Set(['stripe', 'mercadopago', 'pagbank']);

export const PAYMENT_GATEWAY_CATALOG: PaymentGatewayCatalogItem[] = [
  { value: 'stripe', label: 'Stripe', region: 'Global', supportLevel: 'supported' },
  { value: 'mercadopago', label: 'Mercado Pago', region: 'Brasil/LatAm', supportLevel: 'supported' },
  { value: 'pagbank', label: 'PagBank', region: 'Brasil', supportLevel: 'supported' },
  { value: 'paypal', label: 'PayPal', region: 'Global', supportLevel: 'planned' },
  { value: 'adyen', label: 'Adyen', region: 'Global', supportLevel: 'planned' },
  { value: 'authorize_net', label: 'Authorize.Net', region: 'EUA', supportLevel: 'planned' },
  { value: 'braintree', label: 'Braintree', region: 'Global', supportLevel: 'planned' },
  { value: 'checkout_com', label: 'Checkout.com', region: 'Global', supportLevel: 'planned' },
  { value: 'worldpay', label: 'Worldpay', region: 'Global', supportLevel: 'planned' },
  { value: 'square', label: 'Square', region: 'EUA', supportLevel: 'planned' },
  { value: 'razorpay', label: 'Razorpay', region: 'India', supportLevel: 'planned' },
  { value: 'payu', label: 'PayU', region: 'Global/LatAm', supportLevel: 'planned' },
  { value: 'verifone_2checkout', label: '2Checkout', region: 'Global', supportLevel: 'planned' },
  { value: 'klarna', label: 'Klarna', region: 'Europa', supportLevel: 'planned' },
  { value: 'affirm', label: 'Affirm', region: 'EUA', supportLevel: 'planned' },
  { value: 'afterpay', label: 'Afterpay', region: 'Global', supportLevel: 'planned' },
  { value: 'amazon_pay', label: 'Amazon Pay', region: 'Global', supportLevel: 'planned' },
  { value: 'apple_pay', label: 'Apple Pay', region: 'Global', supportLevel: 'planned' },
  { value: 'google_pay', label: 'Google Pay', region: 'Global', supportLevel: 'planned' },
  { value: 'samsung_pay', label: 'Samsung Pay', region: 'Global', supportLevel: 'planned' },
  { value: 'alipay', label: 'Alipay', region: 'Asia', supportLevel: 'planned' },
  { value: 'wechat_pay', label: 'WeChat Pay', region: 'Asia', supportLevel: 'planned' },
  { value: 'dwolla', label: 'Dwolla', region: 'EUA', supportLevel: 'planned' },
  { value: 'iugu', label: 'Iugu', region: 'Brasil', supportLevel: 'planned' },
  { value: 'pagarme', label: 'Pagar.me', region: 'Brasil', supportLevel: 'planned' },
  { value: 'asaas', label: 'Asaas', region: 'Brasil', supportLevel: 'planned' },
  { value: 'efi', label: 'Efí', region: 'Brasil', supportLevel: 'planned' },
  { value: 'cielo', label: 'Cielo', region: 'Brasil', supportLevel: 'planned' },
  { value: 'rede', label: 'Rede', region: 'Brasil', supportLevel: 'planned' },
  { value: 'stone', label: 'Stone', region: 'Brasil', supportLevel: 'planned' },
  { value: 'getnet', label: 'Getnet', region: 'Brasil', supportLevel: 'planned' },
  { value: 'safrapay', label: 'SafraPay', region: 'Brasil', supportLevel: 'planned' },
  { value: 'zoop', label: 'Zoop', region: 'Brasil', supportLevel: 'planned' },
  { value: 'dlocal', label: 'dLocal', region: 'Global/LatAm', supportLevel: 'planned' },
  { value: 'ebanx', label: 'EBANX', region: 'LatAm', supportLevel: 'planned' },
  { value: 'payoneer_checkout', label: 'Payoneer Checkout', region: 'Global', supportLevel: 'planned' },
  { value: 'bluesnap', label: 'BlueSnap', region: 'Global', supportLevel: 'planned' },
  { value: 'paytrace', label: 'PayTrace', region: 'EUA', supportLevel: 'planned' },
  { value: 'payline', label: 'Payline', region: 'EUA', supportLevel: 'planned' },
  { value: 'paytabs', label: 'PayTabs', region: 'MENA', supportLevel: 'planned' },
  { value: 'paystack', label: 'Paystack', region: 'Africa', supportLevel: 'planned' },
  { value: 'flutterwave', label: 'Flutterwave', region: 'Africa', supportLevel: 'planned' },
  { value: 'mollie', label: 'Mollie', region: 'Europa', supportLevel: 'planned' },
  { value: 'revolut_pay', label: 'Revolut Pay', region: 'Europa', supportLevel: 'planned' },
  { value: 'sumup', label: 'SumUp', region: 'Global', supportLevel: 'planned' },
  { value: 'skrill', label: 'Skrill', region: 'Global', supportLevel: 'planned' },
  { value: 'neteller', label: 'Neteller', region: 'Global', supportLevel: 'planned' },
  { value: 'payone', label: 'Payone', region: 'Europa', supportLevel: 'planned' },
  { value: 'moneris', label: 'Moneris', region: 'Canada', supportLevel: 'planned' },
  { value: 'bambora', label: 'Bambora', region: 'Global', supportLevel: 'planned' },
  { value: 'opayo', label: 'Opayo', region: 'Reino Unido', supportLevel: 'planned' },
  { value: 'cybersource', label: 'Cybersource', region: 'Global', supportLevel: 'planned' },
  { value: 'fiserv', label: 'Fiserv', region: 'Global', supportLevel: 'planned' },
  { value: 'nmi', label: 'NMI', region: 'Global', supportLevel: 'planned' },
  { value: 'nuvei', label: 'Nuvei', region: 'Global', supportLevel: 'planned' },
  { value: 'trustly', label: 'Trustly', region: 'Europa', supportLevel: 'planned' },
  { value: 'sezzle', label: 'Sezzle', region: 'Global', supportLevel: 'planned' },
  { value: 'zip', label: 'Zip', region: 'Global', supportLevel: 'planned' },
  { value: 'hyperpay', label: 'HyperPay', region: 'MENA', supportLevel: 'planned' },
  { value: 'telr', label: 'Telr', region: 'MENA', supportLevel: 'planned' },
  { value: 'noon_payments', label: 'Noon Payments', region: 'MENA', supportLevel: 'planned' },
  { value: 'tap_payments', label: 'Tap Payments', region: 'MENA', supportLevel: 'planned' },
  { value: 'myfatoorah', label: 'MyFatoorah', region: 'MENA', supportLevel: 'planned' },
  { value: 'paymob', label: 'Paymob', region: 'MENA/Africa', supportLevel: 'planned' },
  { value: 'iyzico', label: 'iyzico', region: 'Turquia', supportLevel: 'planned' },
  { value: 'paytm', label: 'Paytm', region: 'India', supportLevel: 'planned' },
  { value: 'cashfree', label: 'Cashfree', region: 'India', supportLevel: 'planned' },
  { value: 'ccavenue', label: 'CCAvenue', region: 'India', supportLevel: 'planned' },
  { value: 'billdesk', label: 'BillDesk', region: 'India', supportLevel: 'planned' },
  { value: 'midtrans', label: 'Midtrans', region: 'Indonesia', supportLevel: 'planned' },
  { value: 'xendit', label: 'Xendit', region: 'SEA', supportLevel: 'planned' },
  { value: 'omise', label: 'Omise', region: 'SEA', supportLevel: 'planned' },
  { value: 'paymaya', label: 'PayMaya', region: 'Filipinas', supportLevel: 'planned' },
  { value: 'gcash', label: 'GCash', region: 'Filipinas', supportLevel: 'planned' },
  { value: 'dragonpay', label: 'Dragonpay', region: 'Filipinas', supportLevel: 'planned' },
  { value: 'eway', label: 'eWAY', region: 'Australia', supportLevel: 'planned' },
  { value: 'pinpayments', label: 'Pin Payments', region: 'Australia', supportLevel: 'planned' },
  { value: 'windcave', label: 'Windcave', region: 'Oceania', supportLevel: 'planned' },
  { value: 'transbank', label: 'Transbank', region: 'Chile', supportLevel: 'planned' },
  { value: 'kushki', label: 'Kushki', region: 'LatAm', supportLevel: 'planned' },
  { value: 'placetopay', label: 'Place to Pay', region: 'LatAm', supportLevel: 'planned' },
  { value: 'conekta', label: 'Conekta', region: 'Mexico', supportLevel: 'planned' },
  { value: 'openpay', label: 'Openpay', region: 'Mexico', supportLevel: 'planned' },
  { value: 'senangpay', label: 'SenangPay', region: 'Malasia', supportLevel: 'planned' },
  { value: 'toyyibpay', label: 'ToyyibPay', region: 'Malasia', supportLevel: 'planned' },
  { value: 'payfast', label: 'PayFast', region: 'Africa', supportLevel: 'planned' },
  { value: 'peach_payments', label: 'Peach Payments', region: 'Africa', supportLevel: 'planned' },
  { value: 'pesapal', label: 'Pesapal', region: 'Africa', supportLevel: 'planned' },
  { value: 'momo', label: 'MoMo', region: 'Africa/Asia', supportLevel: 'planned' },
  { value: 'coinbase_commerce', label: 'Coinbase Commerce', region: 'Global', supportLevel: 'planned' },
  { value: 'bitpay', label: 'BitPay', region: 'Global', supportLevel: 'planned' },
  { value: 'coinpayments', label: 'CoinPayments', region: 'Global', supportLevel: 'planned' },
  { value: 'airwallex', label: 'Airwallex', region: 'Global', supportLevel: 'planned' },
  { value: 'rapyd', label: 'Rapyd', region: 'Global', supportLevel: 'planned' },
  { value: 'truelayer', label: 'TrueLayer', region: 'Europa', supportLevel: 'planned' },
  { value: 'go_cardless', label: 'GoCardless', region: 'Global', supportLevel: 'planned' },
  { value: 'stax', label: 'Stax', region: 'EUA', supportLevel: 'planned' },
  { value: 'helcim', label: 'Helcim', region: 'North America', supportLevel: 'planned' },
  { value: 'fortis', label: 'Fortis', region: 'North America', supportLevel: 'planned' },
  { value: 'orbital', label: 'Orbital', region: 'Global', supportLevel: 'planned' },
  { value: 'paysera', label: 'Paysera', region: 'Europa', supportLevel: 'planned' },
  { value: 'vipps', label: 'Vipps', region: 'Nordics', supportLevel: 'planned' },
  { value: 'mobilepay', label: 'MobilePay', region: 'Nordics', supportLevel: 'planned' },
  { value: 'swish', label: 'Swish', region: 'Suécia', supportLevel: 'planned' },
  { value: 'multisafepay', label: 'MultiSafepay', region: 'Europa', supportLevel: 'planned' },
  { value: 'paytrail', label: 'Paytrail', region: 'Finlandia', supportLevel: 'planned' },
];

export const PAYMENT_GATEWAY_CATALOG_MAP = new Map(
  PAYMENT_GATEWAY_CATALOG.map((item) => [item.value, item])
);
