ALTER TABLE "modulos"
ADD COLUMN IF NOT EXISTS "is_pro" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "modulos"
ADD COLUMN IF NOT EXISTS "allowed_roles" "Role"[] NOT NULL DEFAULT ARRAY['DONO_EMPRESA','FUNCIONARIO_EMPRESA']::"Role"[];
